In [1]:
import pandas as pd

In [2]:
import tensorflow as tf

In [3]:
df=pd.read_csv(r"C:\Users\PARIMAL\OneDrive\Desktop\Data Science Internship\Data-Science\Deep leraning\ANN\Credit (1).csv")

In [4]:
df

,age,job,marital,education,balance,housing,duration,campaign,approval
0,30.0,unemployed,married,primary,1787,no,79.0,1,no
1,33.0,services,married,secondary,4789,yes,220.0,1,no
2,35.0,management,single,tertiary,1350,yes,185.0,1,no
3,30.0,management,married,tertiary,1476,yes,199.0,4,no
4,59.0,blue-collar,married,secondary,0,yes,226.0,1,no
...,...,...,...,...,...,...,...,...,...
4516,99.0,services,married,secondary,-333,yes,329.0,5,no
4517,57.0,self-employed,married,tertiary,-3313,yes,-153.0,1,no
4518,57.0,technician,married,secondary,295,no,151.0,11,no
4519,28.0,blue-collar,married,secondary,1137,no,129.0,4,no
4520,44.0,entrepreneur,single,tertiary,1136,yes,345.0,2,no

###### onehot encoder means when we have to encode in the form of 0 and 1 means yes or no
###### and label encoding mein string ko encode karta hai

In [5]:
df['job'].unique()

array(['unemployed', 'services', 'management', 'blue-collar',
       'self-employed', 'technician', 'entrepreneur', 'admin.', 'student',
       'housemaid', 'retired', 'unknown', nan], dtype=object)

In [6]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['job']=le.fit_transform(df['job'])
df['job'].unique()

array([10,  7,  4,  1,  6,  9,  2,  0,  8,  3,  5, 11, 12])

In [7]:
df['marital'].unique()

array(['married', 'single', 'divorced', nan], dtype=object)

In [8]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['marital']=le.fit_transform(df['marital'])
df['marital'].unique()

array([1, 2, 0, 3])

In [9]:
df['education'].unique()

array(['primary', 'secondary', 'tertiary', 'unknown', nan], dtype=object)

In [10]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['education']=le.fit_transform(df['education'])
df['education'].unique()

array([0, 1, 2, 3, 4])

In [11]:
df

,age,job,marital,education,balance,housing,duration,campaign,approval
0,30.0,10,1,0,1787,no,79.0,1,no
1,33.0,7,1,1,4789,yes,220.0,1,no
2,35.0,4,2,2,1350,yes,185.0,1,no
3,30.0,4,1,2,1476,yes,199.0,4,no
4,59.0,1,1,1,0,yes,226.0,1,no
...,...,...,...,...,...,...,...,...,...
4516,99.0,7,1,1,-333,yes,329.0,5,no
4517,57.0,6,1,2,-3313,yes,-153.0,1,no
4518,57.0,9,1,1,295,no,151.0,11,no
4519,28.0,1,1,1,1137,no,129.0,4,no
4520,44.0,2,2,2,1136,yes,345.0,2,no

In [12]:
df['approval'].unique()

array(['no', 'yes'], dtype=object)

In [13]:
approval_dict={'no':0, 'yes':1}

In [14]:
df['approval']=df['approval'].map(approval_dict)

In [15]:
df

,age,job,marital,education,balance,housing,duration,campaign,approval
0,30.0,10,1,0,1787,no,79.0,1,0
1,33.0,7,1,1,4789,yes,220.0,1,0
2,35.0,4,2,2,1350,yes,185.0,1,0
3,30.0,4,1,2,1476,yes,199.0,4,0
4,59.0,1,1,1,0,yes,226.0,1,0
...,...,...,...,...,...,...,...,...,...
4516,99.0,7,1,1,-333,yes,329.0,5,0
4517,57.0,6,1,2,-3313,yes,-153.0,1,0
4518,57.0,9,1,1,295,no,151.0,11,0
4519,28.0,1,1,1,1137,no,129.0,4,0
4520,44.0,2,2,2,1136,yes,345.0,2,0

In [16]:
df['housing'].unique()

array(['no', 'yes', nan], dtype=object)

In [17]:
housing_dict={'no':0, 'yes':1}

In [18]:
df['housing']=df['housing'].map(housing_dict)

In [19]:
df

,age,job,marital,education,balance,housing,duration,campaign,approval
0,30.0,10,1,0,1787,0.0,79.0,1,0
1,33.0,7,1,1,4789,1.0,220.0,1,0
2,35.0,4,2,2,1350,1.0,185.0,1,0
3,30.0,4,1,2,1476,1.0,199.0,4,0
4,59.0,1,1,1,0,1.0,226.0,1,0
...,...,...,...,...,...,...,...,...,...
4516,99.0,7,1,1,-333,1.0,329.0,5,0
4517,57.0,6,1,2,-3313,1.0,-153.0,1,0
4518,57.0,9,1,1,295,0.0,151.0,11,0
4519,28.0,1,1,1,1137,0.0,129.0,4,0
4520,44.0,2,2,2,1136,1.0,345.0,2,0

In [20]:
df.drop_duplicates(inplace=True)

In [21]:
df.dropna(inplace=True)

In [22]:
df.to_csv("cleaned_credit_dataset.csv",index=False)

In [23]:
x=df.drop('approval',axis=1)
y=df[['approval']]

In [24]:
x

       age  job  marital  education  balance  housing  duration  campaign
0     30.0   10        1          0     1787      0.0      79.0         1
1     33.0    7        1          1     4789      1.0     220.0         1
2     35.0    4        2          2     1350      1.0     185.0         1
3     30.0    4        1          2     1476      1.0     199.0         4
4     59.0    1        1          1        0      1.0     226.0         1
...    ...  ...      ...        ...      ...      ...       ...       ...
4516  99.0    7        1          1     -333      1.0     329.0         5
4517  57.0    6        1          2    -3313      1.0    -153.0         1
4518  57.0    9        1          1      295      0.0     151.0        11
4519  28.0    1        1          1     1137      0.0     129.0         4
4520  44.0    2        2          2     1136      1.0     345.0         2

[4513 rows x 8 columns]

In [25]:
y

      approval
0            0
1            0
2            0
3            0
4            0
...        ...
4516         0
4517         0
4518         0
4519         0
4520         0

[4513 rows x 1 columns]

In [26]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [27]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [28]:
input_size=x_train.shape[1]

In [29]:
model = Sequential()
model.add(Dense(units=128,activation='relu',input_shape=(input_size,)))

model.add(Dense(units=64,activation='relu'))
model.add(Dense(units=32,activation='relu'))
model.add(Dense(units=16,activation='relu'))
model.add(Dense(units=8,activation='relu'))

## outer layer
model.add(Dense(units=1,activation='sigmoid'))
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

C:\Users\PARIMAL\AppData\Roaming\Python\Python311\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [30]:
model.fit(x_train,y_train,epochs=10,batch_size=32)

Epoch 1/10
113/113 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7133 - loss: 2.7657
Epoch 2/10
113/113 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8090 - loss: 1.6189
Epoch 3/10
113/113 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8514 - loss: 0.5529
Epoch 4/10
113/113 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8677 - loss: 0.4641
Epoch 5/10
113/113 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8642 - loss: 0.8662
Epoch 6/10
113/113 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7806 - loss: 3.4221
Epoch 7/10
113/113 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8692 - loss: 2.8321
Epoch 8/10
113/113 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8685 - loss: 1.1449
Epoch 9/10
113/113 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8575 - loss: 12.1501
Epoch 10/10
113/113 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8463 - loss: 2.0011

In [31]:
pred = model.predict(x_test)
pred

29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step

array([[2.33520712e-19],
       [2.18675390e-01],
       [3.86847645e-01],
       [1.76554325e-03],
       [2.30026126e-04],
       [4.29349566e-05],
       [2.11308835e-14],
       [3.59853417e-01],
       [7.07126632e-02],
       [1.04323099e-05],
       [1.00536016e-20],
       [8.81438404e-02],
       [2.85427286e-05],
       [4.45659832e-21],
       [0.00000000e+00],
       [7.03313276e-02],
       [4.93308067e-01],
       [5.73954004e-08],
       [7.23639220e-14],
       [6.56217694e-01],
       [2.16484155e-14],
       [3.00624102e-01],
       [5.16042586e-09],
       [3.86249885e-04],
       [2.58185606e-09],
       [1.43732250e-01],
       [3.43462288e-01],
       [8.73832285e-01],
       [1.28403232e-02],
       [3.16471368e-01],
       [3.05341631e-01],
       [1.29756751e-03],
       [1.03860521e-06],
       [1.87625017e-06],
       [8.65337801e-11],
       [3.22556794e-01],
       [6.96177176e-06],
       [2.75883025e-07],
       [9.80846584e-03],
       [3.39923776e-04],
       [1.72225554e-02],
       [2.89601624e-01],
       [1.51068727e-02],
       [1.70946296e-03],
       [2.62934826e-02],
       [3.05477470e-01],
       [7.03670958e-04],
       [2.86139622e-02],
       [2.30957059e-10],
       [4.99307702e-04],
       [1.86291683e-14],
       [2.66167310e-10],
       [3.07853241e-03],
       [7.26520631e-31],
       [1.72271684e-04],
       [4.06577414e-13],
       [5.37548661e-01],
       [1.83284748e-02],
       [1.26655968e-05],
       [7.49882281e-01],
       [9.06521448e-16],
       [8.99349060e-03],
       [1.76137690e-33],
       [1.65661544e-01],
       [1.12136632e-30],
       [4.35636350e-04],
       [1.73419963e-07],
       [3.06920251e-23],
       [1.62776280e-03],
       [8.93672986e-04],
       [2.16961786e-01],
       [4.70985711e-01],
       [3.79473031e-01],
       [1.51228314e-14],
       [2.56608546e-01],
       [5.40187066e-05],
       [5.04322001e-04],
       [3.36741775e-01],
       [4.28850672e-06],
       [1.98301961e-04],
       [1.65807048e-03],
       [4.19433713e-02],
       [4.62806132e-03],
       [9.90943611e-03],
       [5.82754467e-07],
       [8.08771178e-02],
       [4.93977325e-07],
       [2.47079343e-01],
       [2.08867639e-01],
       [1.17229559e-01],
       [2.94735713e-07],
       [0.00000000e+00],
       [4.32264894e-01],
       [6.90964283e-03],
       [2.14942644e-04],
       [9.69082962e-21],
       [6.09035254e-01],
       [9.69453353e-08],
       [4.79437828e-01],
       [1.17196083e-01],
       [7.90116417e-09],
       [4.56826359e-01],
       [1.31242280e-03],
       [9.13435295e-02],
       [3.67507567e-07],
       [5.18432644e-04],
       [9.83002906e-08],
       [6.18483406e-03],
       [3.59656778e-03],
       [4.06093001e-01],
       [2.10820466e-01],
       [4.67452765e-01],
       [8.15640262e-04],
       [1.23613617e-07],
       [4.78943053e-04],
       [6.49943650e-02],
       [6.83475984e-03],
       [2.34685410e-10],
       [5.67831476e-11],
       [5.26541771e-05],
       [3.93150091e-01],
       [1.92701712e-08],
       [5.48182470e-06],
       [2.93671670e-10],
       [1.06415160e-01],
       [2.01942101e-01],
       [7.40286894e-04],
       [3.99560528e-03],
       [7.49545870e-03],
       [1.07842337e-12],
       [1.44555219e-04],
       [7.63859134e-03],
       [1.48840964e-24],
       [4.86212492e-09],
       [5.73239103e-02],
       [3.52144130e-02],
       [1.09177071e-03],
       [3.20560594e-06],
       [1.40201747e-02],
       [9.49698119e-07],
       [2.63518602e-01],
       [6.60912171e-02],
       [5.99049347e-13],
       [1.49209845e-05],
       [3.48968804e-01],
       [2.56198086e-03],
       [2.20330688e-03],
       [2.08579077e-05],
       [5.98196648e-02],
       [1.04432565e-03],
       [3.40340662e-08],
       [7.19363859e-13],
       [3.11444728e-06],
       [2.00370610e-01],
       [3.81910395e-05],
       [5.05504385e-02],
       [4.47316915e-02],
       [2.59668142e-01],
       [3.17447275e-01],
       [3.51880258e-09],
       [3.59486222e-01],
       [5.54159957e-17],
       [5.94639965e-14],
       [4.92242165e-03],
       [4.87053573e-01],
       [1.43652231e-01],
       [5.81880705e-03],
       [2.29849084e-05],
       [7.54725695e-01],
       [3.01534414e-01],
       [3.37825184e-10],
       [3.25755477e-02],
       [3.78496334e-05],
       [5.30251861e-01],
       [4.76727113e-02],
       [3.37068667e-03],
       [2.58158217e-03],
       [4.79650110e-01],
       [2.85347586e-16],
       [3.65552723e-01],
       [7.65407979e-01],
       [5.37513375e-01],
       [9.84255660e-17],
       [1.92670839e-08],
       [6.70233555e-03],
       [3.34733933e-01],
       [2.22040340e-03],
       [6.04727818e-03],
       [1.93030402e-01],
       [4.04881405e-07],
       [1.52077153e-01],
       [9.77133572e-01],
       [1.61702530e-07],
       [3.80988349e-03],
       [3.41214531e-04],
       [3.18264633e-01],
       [1.07794004e-12],
       [2.91278742e-12],
       [9.94049668e-01],
       [1.40781020e-04],
       [8.63781846e-09],
       [0.00000000e+00],
       [1.14578230e-03],
       [6.60547893e-03],
       [4.97166485e-01],
       [1.16732679e-23],
       [1.46080536e-04],
       [1.60746349e-05],
       [3.38821039e-02],
       [1.74599292e-03],
       [7.36173335e-03],
       [1.93570570e-17],
       [1.73578576e-06],
       [3.07565480e-01],
       [7.63016695e-04],
       [1.27054565e-02],
       [0.00000000e+00],
       [2.61397404e-03],
       [1.91938359e-08],
       [4.46324499e-04],
       [2.67095298e-01],
       [5.94850659e-01],
       [1.32373320e-02],
       [2.27570851e-07],
       [5.60756922e-02],
       [6.65199850e-03],
       [3.63582909e-01],
       [7.64985606e-02],
       [2.00881586e-05],
       [8.32133917e-09],
       [1.13152119e-03],
       [4.61511552e-01],
       [1.67232037e-01],
       [3.41840714e-01],
       [2.84143089e-15],
       [2.62023240e-01],
       [2.86232753e-05],
       [1.43854558e-01],
       [3.93708125e-02],
       [8.81711662e-01],
       [1.19756014e-05],
       [4.87276688e-02],
       [5.83158631e-04],
       [2.92132259e-03],
       [6.48331642e-01],
       [2.07542317e-12],
       [3.07881040e-04],
       [1.25681190e-02],
       [3.49248806e-03],
       [4.05627043e-09],
       [4.25897199e-23],
       [2.67028213e-01],
       [2.40725085e-01],
       [2.77831107e-01],
       [2.65930168e-04],
       [6.42460824e-12],
       [3.58307148e-06],
       [7.91220648e-12],
       [1.85167558e-11],
       [3.91070126e-03],
       [4.50204496e-08],
       [2.50096112e-01],
       [2.65622977e-03],
       [1.16977770e-32],
       [6.19670958e-04],
       [3.87854092e-02],
       [5.27700642e-04],
       [2.39993988e-05],
       [5.59538245e-01],
       [3.69111508e-01],
       [3.95700969e-02],
       [8.13933315e-19],
       [3.59533180e-04],
       [4.57421003e-04],
       [9.98932496e-02],
       [2.90400535e-01],
       [1.76055655e-01],
       [4.29968728e-04],
       [6.12371117e-02],
       [8.02253421e-19],
       [1.12564163e-02],
       [8.94984789e-03],
       [4.32942179e-05],
       [5.89214405e-03],
       [7.87691653e-01],
       [1.20504781e-31],
       [3.60044651e-05],
       [3.67940928e-10],
       [3.87476897e-03],
       [2.38105357e-01],
       [3.23840529e-01],
       [3.86194885e-01],
       [8.18806142e-03],
       [8.85244925e-03],
       [2.25594533e-07],
       [1.68226707e-05],
       [5.97381984e-07],
       [1.61766431e-31],
       [2.62495279e-01],
       [1.65633003e-06],
       [7.76141729e-09],
       [1.86887363e-11],
       [9.70496833e-02],
       [4.22640115e-01],
       [8.71013403e-02],
       [2.05225274e-02],
       [8.70741438e-03],
       [1.94296905e-11],
       [1.92245152e-02],
       [1.33373216e-03],
       [4.00182933e-01],
       [5.03495522e-03],
       [3.72124574e-04],
       [3.81096988e-03],
       [2.98334686e-12],
       [1.10313155e-01],
       [1.16446432e-20],
       [2.63419217e-11],
       [2.60979228e-04],
       [2.77296752e-01],
       [6.64617587e-03],
       [1.58328623e-01],
       [4.44065779e-01],
       [4.16701743e-11],
       [1.93240009e-02],
       [4.57208706e-08],
       [3.33318472e-01],
       [3.54764852e-05],
       [3.67441595e-01],
       [4.50702426e-17],
       [2.22385824e-02],
       [5.83793502e-04],
       [1.19637977e-02],
       [2.58478671e-01],
       [7.77687092e-05],
       [3.71918231e-01],
       [1.15067074e-02],
       [1.40508533e-01],
       [1.68318406e-01],
       [1.43361649e-05],
       [1.40306851e-22],
       [3.48434458e-03],
       [4.58206028e-01],
       [5.95203698e-01],
       [2.62179881e-01],
       [1.72702700e-03],
       [1.33357085e-02],
       [1.92200840e-02],
       [4.17198539e-01],
       [6.90273650e-04],
       [2.65137992e-08],
       [1.73922370e-25],
       [8.68015729e-11],
       [1.96798146e-02],
       [2.05347005e-05],
       [1.13402413e-04],
       [1.60829499e-01],
       [1.99417293e-01],
       [8.61087841e-08],
       [3.06804490e-04],
       [4.02103424e-01],
       [1.32275388e-01],
       [9.64426324e-02],
       [5.38358780e-27],
       [6.97579443e-18],
       [1.67536564e-04],
       [1.01919927e-01],
       [4.67004478e-01],
       [5.60609857e-03],
       [4.52212512e-01],
       [2.64197767e-01],
       [5.61320782e-01],
       [3.72200638e-01],
       [6.38661608e-02],
       [1.40367270e-01],
       [2.26402881e-16],
       [2.22333465e-02],
       [6.11740589e-01],
       [2.60997540e-03],
       [4.93209541e-07],
       [6.04146253e-03],
       [3.62608407e-04],
       [5.09431839e-01],
       [1.44742295e-01],
       [3.89430635e-02],
       [5.22809387e-08],
       [1.58162251e-01],
       [2.73747974e-05],
       [1.60860080e-15],
       [1.44481608e-13],
       [6.22671962e-01],
       [1.62800145e-03],
       [1.79861918e-01],
       [5.74122566e-07],
       [2.50011504e-01],
       [1.90405831e-01],
       [1.75756384e-02],
       [4.64287736e-02],
       [1.28219426e-01],
       [7.52966404e-01],
       [3.28097213e-03],
       [3.71465832e-01],
       [2.83876300e-01],
       [6.00473166e-01],
       [1.91326020e-04],
       [1.28460988e-01],
       [8.21932927e-02],
       [4.08781528e-01],
       [1.70083404e-01],
       [2.17364341e-01],
       [2.43227452e-01],
       [2.42896913e-14],
       [4.09764677e-01],
       [4.39022154e-01],
       [3.24116014e-02],
       [4.00515556e-01],
       [2.96848953e-01],
       [1.52505643e-03],
       [4.98770212e-04],
       [6.58140317e-13],
       [6.12137256e-08],
       [5.23207545e-01],
       [8.25500734e-09],
       [2.77528286e-01],
       [1.54135269e-04],
       [1.55570480e-04],
       [8.28113127e-03],
       [8.25210273e-01],
       [2.71281600e-03],
       [5.71366072e-01],
       [2.26570002e-04],
       [2.78850375e-30],
       [1.02026468e-06],
       [3.51494610e-01],
       [1.42903666e-11],
       [4.26853512e-04],
       [9.82123077e-01],
       [1.07596304e-06],
       [1.06500439e-01],
       [4.64764178e-01],
       [2.27390584e-02],
       [5.70420250e-02],
       [3.23986524e-06],
       [1.16410237e-02],
       [1.38335818e-04],
       [4.12310765e-05],
       [2.84283423e-08],
       [8.02080333e-02],
       [2.00612902e-07],
       [1.64367631e-01],
       [3.92574370e-01],
       [2.04844822e-12],
       [1.18101831e-04],
       [1.70132742e-04],
       [9.48287267e-03],
       [8.91661569e-02],
       [1.04648134e-05],
       [5.81639886e-01],
       [4.48091000e-01],
       [1.59697041e-01],
       [3.91495600e-02],
       [1.34899840e-02],
       [9.83058989e-01],
       [1.10268150e-03],
       [3.61740706e-03],
       [7.06025511e-02],
       [4.93045241e-01],
       [5.73266018e-03],
       [1.09476075e-01],
       [2.84505238e-16],
       [3.83430102e-04],
       [3.86817800e-03],
       [4.08779353e-01],
       [3.26029933e-03],
       [4.11023805e-03],
       [1.35524943e-02],
       [5.19932853e-03],
       [8.24166287e-04],
       [3.74939620e-01],
       [2.76756316e-01],
       [2.36073285e-01],
       [2.65000284e-01],
       [1.86097118e-36],
       [3.43795630e-14],
       [1.50016058e-06],
       [6.86089462e-03],
       [2.19399699e-05],
       [2.07691342e-01],
       [7.88554499e-11],
       [3.28821629e-01],
       [1.78847678e-29],
       [1.87071171e-02],
       [9.39013250e-03],
       [3.04869264e-02],
       [6.66117614e-07],
       [1.45466670e-01],
       [4.42340570e-05],
       [2.57831663e-02],
       [1.34458720e-12],
       [2.58759782e-03],
       [2.61542411e-03],
       [1.97438478e-01],
       [1.30037474e-13],
       [7.25085556e-05],
       [2.40285248e-01],
       [1.55402884e-01],
       [1.83017629e-11],
       [4.12269431e-17],
       [1.08318664e-02],
       [1.11917071e-02],
       [3.91352326e-01],
       [4.83317818e-38],
       [4.06915701e-09],
       [8.24180484e-01],
       [4.51131072e-03],
       [7.93978851e-03],
       [2.48295262e-01],
       [2.43016835e-34],
       [4.77765650e-02],
       [2.81385612e-02],
       [3.06392349e-02],
       [9.39906836e-02],
       [1.62248686e-02],
       [4.35742140e-02],
       [2.53810850e-03],
       [5.98981569e-05],
       [6.59617854e-07],
       [6.98331073e-02],
       [3.02368408e-11],
       [3.21522653e-02],
       [1.03068139e-07],
       [1.37997046e-02],
       [1.96745783e-01],
       [3.74870718e-01],
       [1.00392602e-01],
       [1.66014151e-03],
       [4.11565416e-03],
       [3.27130198e-01],
       [2.43931674e-04],
       [2.39715025e-01],
       [5.59530022e-09],
       [1.21403127e-06],
       [8.32607050e-09],
       [4.14860854e-12],
       [8.92509799e-03],
       [4.13327850e-02],
       [4.81985137e-02],
       [1.89645786e-03],
       [2.10408792e-02],
       [1.03774080e-02],
       [1.33753428e-02],
       [2.80855056e-02],
       [4.29443195e-02],
       [2.62416269e-11],
       [1.42392833e-02],
       [3.45958352e-01],
       [1.54728442e-01],
       [1.80824757e-01],
       [3.20136935e-01],
       [2.25865133e-02],
       [3.81071438e-18],
       [1.25132658e-07],
       [2.49370653e-02],
       [5.40870190e-01],
       [4.52855900e-02],
       [8.53210688e-04],
       [4.46073748e-02],
       [1.63212851e-01],
       [2.67112341e-13],
       [1.51374206e-01],
       [1.90936886e-02],
       [7.02389942e-14],
       [1.79714755e-06],
       [3.27923400e-09],
       [5.45468135e-03],
       [7.39139330e-04],
       [8.86319578e-02],
       [2.78255343e-03],
       [2.63820681e-07],
       [9.44020748e-02],
       [1.94900102e-04],
       [9.74267884e-15],
       [1.14010505e-12],
       [5.87474346e-01],
       [1.72566883e-02],
       [6.53283088e-04],
       [8.23788404e-01],
       [1.38886367e-06],
       [2.90525408e-04],
       [4.89933463e-03],
       [1.44613890e-10],
       [8.88874568e-03],
       [2.01522037e-01],
       [4.55431800e-05],
       [1.28559762e-07],
       [2.72670276e-02],
       [2.20371708e-02],
       [4.96607542e-01],
       [7.84231759e-07],
       [1.47553256e-15],
       [6.42518923e-02],
       [9.10453320e-01],
       [1.88542038e-01],
       [3.56483579e-01],
       [9.63857237e-05],
       [3.76780663e-04],
       [3.14422190e-01],
       [1.72632816e-03],
       [6.38890604e-04],
       [6.71026260e-02],
       [9.93613617e-20],
       [1.18622616e-01],
       [1.22391002e-05],
       [7.37005591e-01],
       [2.31034711e-01],
       [3.91512290e-02],
       [8.13536048e-01],
       [3.72689169e-06],
       [1.30792083e-02],
       [6.10797759e-03],
       [3.48746687e-01],
       [2.23862287e-03],
       [5.84278769e-06],
       [1.17438103e-20],
       [2.60973632e-01],
       [5.13509288e-03],
       [4.55611289e-01],
       [4.40438986e-01],
       [1.38991429e-02],
       [2.41384667e-04],
       [3.81010957e-03],
       [4.89068981e-08],
       [8.02577808e-02],
       [7.68123951e-04],
       [1.87937066e-01],
       [9.90168481e-09],
       [3.22838133e-07],
       [7.73954272e-01],
       [3.12117875e-01],
       [5.25252495e-26],
       [1.42195713e-04],
       [5.59050228e-08],
       [9.28759128e-02],
       [3.34911820e-10],
       [5.89687228e-01],
       [1.78406117e-05],
       [3.64348382e-01],
       [5.45800567e-01],
       [1.99592079e-10],
       [4.19041514e-01],
       [2.01548178e-09],
       [7.44111044e-03],
       [6.70797250e-04],
       [4.03833669e-03],
       [2.63412716e-03],
       [6.25589673e-05],
       [1.03428073e-01],
       [4.49396551e-01],
       [2.11855833e-04],
       [8.26062959e-13],
       [1.88146762e-10],
       [1.29107416e-01],
       [2.90621579e-01],
       [2.66972244e-01],
       [2.49410257e-01],
       [1.01571408e-04],
       [5.28268702e-03],
       [4.17726725e-01],
       [3.28599177e-02],
       [9.96290028e-01],
       [7.26116169e-03],
       [5.78306675e-01],
       [2.43746019e-08],
       [7.82576483e-03],
       [2.06133956e-03],
       [9.80069308e-05],
       [2.83335559e-08],
       [1.72399413e-02],
       [1.51162368e-07],
       [6.79084915e-05],
       [2.78157651e-01],
       [1.72740910e-02],
       [2.58353651e-01],
       [4.46629263e-02],
       [9.86686102e-13],
       [8.32528114e-01],
       [5.36827028e-01],
       [1.68250088e-04],
       [1.98297929e-02],
       [1.18393183e-01],
       [7.81524108e-08],
       [4.04433459e-01],
       [4.73561768e-09],
       [1.42800525e-01],
       [3.82906832e-02],
       [7.23342586e-04],
       [6.96263075e-01],
       [1.45624508e-05],
       [9.72207315e-11],
       [9.02136602e-03],
       [2.38399237e-01],
       [1.05101836e-03],
       [2.28668272e-01],
       [6.48980029e-03],
       [5.32404594e-02],
       [3.17072153e-01],
       [1.19998551e-03],
       [7.39391544e-04],
       [2.72433847e-01],
       [9.86748637e-06],
       [1.82288930e-01],
       [3.15575022e-07],
       [6.90504489e-03],
       [8.61468792e-01],
       [2.73792357e-05],
       [1.23590313e-01],
       [5.96513748e-01],
       [2.44927377e-01],
       [1.46797311e-03],
       [3.97916526e-01],
       [2.65264418e-04],
       [1.28309699e-02],
       [2.95798797e-02],
       [1.16579587e-12],
       [9.39248363e-04],
       [1.00436955e-06],
       [2.57850081e-01],
       [3.16633314e-01],
       [1.32448405e-19],
       [8.52571902e-05],
       [1.80965304e-04],
       [2.29286710e-16],
       [3.50377828e-01],
       [1.33301201e-03],
       [5.07730245e-20],
       [3.92881989e-01],
       [2.54636481e-02],
       [3.09651438e-03],
       [2.42631696e-02],
       [7.86550492e-02],
       [3.03957518e-02],
       [1.27914355e-08],
       [5.23355696e-03],
       [5.82197607e-02],
       [2.10207999e-01],
       [1.47822499e-01],
       [4.77888039e-04],
       [2.79005349e-01],
       [2.55764365e-01],
       [7.36445069e-01],
       [1.98753905e-02],
       [3.82853183e-03],
       [3.31163071e-02],
       [5.01462840e-04],
       [3.82394254e-01],
       [9.69503218e-16],
       [8.85949433e-01],
       [4.71643545e-02],
       [1.15743149e-02],
       [2.97022313e-01],
       [5.93080044e-01],
       [2.85826683e-01],
       [2.39275942e-05],
       [1.80074537e-07],
       [3.87998689e-10],
       [1.62618235e-04],
       [2.50994325e-01],
       [2.96126395e-01],
       [3.46515447e-01],
       [2.95127761e-02],
       [1.01476982e-02],
       [1.73075416e-03],
       [3.98162864e-02],
       [1.39477521e-01],
       [3.70352459e-03],
       [4.38630877e-06],
       [5.62180758e-01],
       [1.47387153e-03],
       [2.94226259e-01],
       [5.93177900e-02],
       [3.15781457e-10],
       [7.07538500e-02],
       [1.86993589e-07],
       [2.60295277e-03],
       [9.76289739e-05],
       [8.10425580e-02],
       [1.47693828e-01],
       [1.02011685e-14],
       [2.98558325e-01],
       [1.49698451e-01],
       [5.86096081e-04],
       [1.36930391e-01],
       [2.28352263e-04],
       [3.56410384e-01],
       [2.91762000e-04],
       [3.87824625e-02],
       [4.12782103e-01],
       [3.37965757e-01],
       [5.86955226e-04],
       [4.12524948e-21],

In [32]:
pred_labels = (pred > 0.5).astype(int)
pred_labels

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0]])

In [33]:
pred = pd.DataFrame(pred)
pred

                0
0    2.335207e-19
1    2.186754e-01
2    3.868476e-01
3    1.765543e-03
4    2.300261e-04
..            ...
898  2.263866e-01
899  0.000000e+00
900  1.357155e-02
901  2.671538e-01
902  2.055853e-01

[903 rows x 1 columns]

In [34]:
pd.concat([y_test,pred],axis=1)

      approval         0
4150       0.0       NaN
2844       0.0       NaN
841        0.0  0.142567
1467       1.0       NaN
1493       0.0       NaN
...        ...       ...
898        NaN  0.226387
899        NaN  0.000000
900        NaN  0.013572
901        NaN  0.267154
902        NaN  0.205585

[1612 rows x 2 columns]